# Change these first
owner: gitetsu # Your GitHub organization or username, where this repository lives
repo: librex-instances-upptime # The name of this repository

sites:
  - name: search.femboy.hu
    url: https://search.femboy.hu/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/hu.png
  - name: lx.vern.cc
    url: https://lx.vern.cc/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: lx.sesu.cc
    url: https://lx.sesu.cc/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/cl.png
  - name: librex.mikata.ru
    url: https://librex.mikata.ru/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: librex.terryiscool160.xyz
    url: https://librex.terryiscool160.xyz/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/uk.png
  - name: search.milivojevic.in.rs
    url: https://search.milivojevic.in.rs/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/nl.png
  - name: librex.nekus.gay
    url: https://librex.nekus.gay/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/pl.png
  - name: search.davidovski.xyz
    url: https://search.davidovski.xyz/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/uk.png
  - name: search.funami.tech
    url: https://search.funami.tech/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/kr.png
  - name: search.madreyk.xyz
    url: https://search.madreyk.xyz/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: search.pabloferreiro.es
    url: https://search.pabloferreiro.es/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: buscar.weblibre.org
    url: https://buscar.weblibre.org/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/cl.png
  - name: search.ahwx.org
    url: https://search.ahwx.org/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/nl.png
  - name: librex.pufe.org
    url: https://librex.pufe.org/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/nz.png
  - name: librex.ratakor.com
    url: https://librex.ratakor.com/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/fr.png
  - name: search.tildevarsh.in
    url: https://search.tildevarsh.in/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/in.png
  - name: librex.myroware.eu
    url: https://librex.myroware.eu/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: search.mascotboi.xyz
    url: https://search.mascotboi.xyz/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/in.png
  - name: lx.drain.win
    url: https://lx.drain.win/
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/sg.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /librex-instances-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: LibreX Instances Upptime
  introTitle: LibreX Instances Upptime
  introMessage: This status page monitors [LibreX instances](https://github.com/hnhx/librex) for uptime.
  navbar:
    - title: Status
      href: /librex-instances-upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
